### ISSUE TITLE
[RELEASE] Leadspicker (NEW)

### ISSUE THREAD

**Issue by vtalas** [clientIO/appmixer-connectors#4]

**Comment by RamBachkheti** [comment]
@vtalas/ @vtalas: I observed following UI issues:

1: Tooltip  is not showing the summary of connector, instead of it shows the component name, please see the following image:
![Image](https://github.com/clientIO/appmixer-connectors/assets/2291263/4e65dad1-66cf-40b3-99f3-6bf80ff092b4)
<hr> 

2: Need to remove extra padding from bottom of action summary text, please see the following image:  
![Image](https://github.com/clientIO/appmixer-connectors/assets/2291263/1e922594-c518-4380-bf30-88fa83214952)

**Comment by vtalas** [comment]
@RamBachkheti ready for re-test

**Comment by vtalas** [comment]
verified on QA
updated description and unify the actions and triggers description 
![image](https://github.com/clientIO/appmixer-connectors/assets/927250/7230b16f-f5bf-4910-9560-b7824626d88d)
